// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	User
	RegisterRequest
	LoginRequest
	LoginResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User_Sex int32

const (
	User_MAN   User_Sex = 0
	User_WOMEN User_Sex = 1
)

var User_Sex_name = map[int32]string{
	0: "MAN",
	1: "WOMEN",
}
var User_Sex_value = map[string]int32{
	"MAN":   0,
	"WOMEN": 1,
}

func (x User_Sex) String() string {
	return proto.EnumName(User_Sex_name, int32(x))
}
func (User_Sex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type User struct {
	Id       uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Nickname string   `protobuf:"bytes,4,opt,name=nickname" json:"nickname,omitempty"`
	Sex      User_Sex `protobuf:"varint,5,opt,name=sex,enum=protocol.User_Sex" json:"sex,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetSex() User_Sex {
	if m != nil {
		return m.Sex
	}
	return User_MAN
}

type RegisterRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AccessToken string `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*RegisterRequest)(nil), "protocol.RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "protocol.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protocol.LoginResponse")
	proto.RegisterEnum("protocol.User_Sex", User_Sex_name, User_Sex_value)
}

func init() { proto.RegisterFile("users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0x31, 0x4b, 0xc3, 0x50,
	0x10, 0xc7, 0xfb, 0x92, 0xb6, 0xb6, 0x57, 0x5b, 0xcb, 0x0d, 0x9a, 0x66, 0x0a, 0x0f, 0x87, 0x4c,
	0x01, 0xeb, 0x20, 0xb8, 0x39, 0x28, 0x08, 0xb6, 0x42, 0xa2, 0x38, 0xc7, 0xe4, 0x28, 0xa1, 0x9a,
	0x17, 0x73, 0x29, 0x66, 0xf1, 0x13, 0xf9, 0x25, 0xe5, 0x25, 0x8d, 0x6d, 0x14, 0x5c, 0x9c, 0x1e,
	0x77, 0x3f, 0xee, 0xde, 0xef, 0x7f, 0x30, 0xda, 0x30, 0xe5, 0xec, 0x65, 0xb9, 0x2a, 0x14, 0x0e,
	0xaa, 0x27, 0x52, 0x2f, 0xf2, 0x53, 0x40, 0xf7, 0x91, 0x29, 0xc7, 0x09, 0x18, 0x49, 0x6c, 0x09,
	0x47, 0xb8, 0x63, 0xdf, 0x48, 0x62, 0xb4, 0x61, 0xa0, 0x27, 0xd2, 0xf0, 0x95, 0x2c, 0xc3, 0x11,
	0xee, 0xd0, 0xff, 0xae, 0x35, 0xcb, 0x42, 0xe6, 0x77, 0x95, 0xc7, 0x96, 0x59, 0xb3, 0xa6, 0xd6,
	0x2c, 0x4d, 0xa2, 0x75, 0x35, 0xd7, 0xad, 0x59, 0x53, 0xe3, 0x29, 0x98, 0x4c, 0xa5, 0xd5, 0x73,
	0x84, 0x3b, 0x99, 0xa3, 0xd7, 0x48, 0x78, 0x5a, 0xc0, 0x0b, 0xa8, 0xf4, 0x35, 0x96, 0x33, 0x30,
	0x03, 0x2a, 0xf1, 0x00, 0xcc, 0xc5, 0xd5, 0x72, 0xda, 0xc1, 0x21, 0xf4, 0x9e, 0xee, 0x17, 0xd7,
	0xcb, 0xa9, 0x90, 0xb7, 0x70, 0xe4, 0xd3, 0x2a, 0xe1, 0x82, 0x72, 0x9f, 0xde, 0x36, 0xc4, 0x45,
	0xcb, 0x53, 0xfc, 0xe1, 0x69, 0xb4, 0x3d, 0xe5, 0x0d, 0x1c, 0xde, 0xa9, 0x55, 0x92, 0xfe, 0x77,
	0xcf, 0x19, 0x8c, 0xb7, 0x7b, 0x38, 0x53, 0x29, 0x13, 0x3a, 0x30, 0x0a, 0xa3, 0x88, 0x98, 0x1f,
	0xd4, 0x9a, 0xd2, 0xed, 0xae, 0xfd, 0xd6, 0xfc, 0x03, 0xfa, 0x81, 0x8e, 0xcc, 0x78, 0x01, 0x83,
	0x26, 0x0f, 0xce, 0x76, 0xf7, 0xf8, 0x91, 0xd1, 0x9e, 0xb4, 0x4f, 0x25, 0x3b, 0x78, 0x09, 0xbd,
	0xea, 0x57, 0x3c, 0xde, 0xa1, 0xfd, 0x38, 0xf6, 0xc9, 0xaf, 0x7e, 0xad, 0x27, 0x3b, 0xcf, 0xfd,
	0x8a, 0x9c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x04, 0x97, 0x93, 0x3b, 0x12, 0x02, 0x00, 0x00,
}
